#!/bin/bash
# build ros_package directly on raspberry instead of cross-compiling for arm64 (but it take some time for the orb_slam_package)
su - ubuntu -c ". /opt/ros/melodic/setup.bash && cd /home/ubuntu/catkin_ws && catkin_make -j2"